description="""
copy assignment – overwrites an exiting collection by another collection (aka deep copy)

Test case:
* Empty collection is created. 
* N number of Stress_ball() is/are inserted using insert_item().
* Copy assignment is used and checked if the data is getting copied.

If this case does not pass, you can check if:
* Collections have default constructor which accepts capacity as argument.
* Insert_item(), total_items() are defined and working.
* "=" operator is used for copy assignment. What has to be done to assign an object to another?
* total_items of the object that is copied is same as the original object.
* What happens with memory locations  of objects when a copy assignment is used. Are they same or different?
* What happens when copy assignment is called on object that already has data?
"""

# Testing self-assignment protection
[adapters.gtest]
compiler_options="-Wextra -Wall"
