title="operator[]"
description="""
To directly access a stress ball in a collection, overload the bracket operator operator[]. It will access
a stress ball in array at position i where i starts from 0 through size-1:
Stress_ball& operator[](int i);

Test case:
* Collection object is created.
* items are inserted with insert_item()
* Item is accessed using []

If this case does not pass, you can check if:
* Collection constructor is well defined.
* [] is overloaded properly. 
* insert_item() , stess_ball constructors, get_color(), get_size() are working properly.
"""
points=4.0

[adapters.gtest]
name="BRACKET"
testfile="bracket.cpp"
