description="""
insert a stress ball to the collection:
void insert_item(const Stress_ball& sb);
If the collection is full, increase the array by doubling its capacity. Use the private helper function
resize() to complete this task. The function resize() should double the capacityof the array and
correctly copy elements from the old array to a new array.

Test case:
* Create collection object.
* Insert items using Insert_item 
* Count the items.

If this case does not pass, you can check if:
* Collection constructor is defined.
* insert_items, resize, total_items() functions are defined.
* initial "capacity" is less than or more than number of insertions into the collection.
* In resize function, make sure capacity is not 0 while performing capacity*2
* In resize function, check use of delete[] 
"""
points=2.0