title="union"
description="""
a union operation that combines the contents of two collections into a third collection (the contents of c1
and c2 are not changed and the order of combination doesn’t matter):
Collection make_union(const Collection& c1, const Collection& c2);

Test case:
* Collection object is created.
* Stress_balls are inserted with insert_item()
* insert_items, make_union and check total_items

If this case does not pass, you can check if:
* Collection constructor is well defined.
* insert_item, resize, total_items, constructors, assignment functions work properly
* make_union, insert_item, total_item (including size and color) are defined.
"""
points=8.0

[adapters.gtest]
name="MAKE_UNION"
testfile="make_union.cpp"
