description="""
return the total number of stress balls in the collection:
int total_items() const;

Test case:
* Collection object is created.
* items are inserted with insert_item()
* total_items(). Total items in the Collection object

If this case does not pass, you can check if:
* Collection constructor is well defined.
* insert_item() , stess_ball constructors are working properly.
"""
points=2.0