title="Insertion operator >>"
description="""
input operator (reading from a file):
istream& operator(istream& is, Collection& c);
reads from the istream is pairs in this format: color size (no parentheses or colons, just a space to
separate them). As colors use strings (you can use STL class string here): red, blue, yellow, green,
and as sizes use strings: small, medium, large. It would be good to have a conversion from string to the
respective enum class value. You need to read from an input file where each pair is in one line. Use at least
two input files: stress_ball1.data and stress_ball2.data for two collections.

Test case:
* Collection object is created.
* Input file is read
* >> operator is used to read contents from file to collection object

If this case does not pass, you can check if:
* Collection constructor is well defined.
* In your compiler, try a sample file and print to check if the contents of the file and object match.
* total_items() (for size and color as well) is working properly.
"""
poitns=4.0

[adapters.gtest]
name="INSERTION"
testfile="insertion.cpp"