title="swap"
description="""
a swap operation that swaps two collections:
void swap(Collection& c1, Collection& c2);
Use the move constructor and move assignment to do this. Do not copy the collection elements.

Test case:
* Collection object is created
* Stress_balls are inserted using insert_item()
* swap() and check total_items()

If this case does not pass, you can check if:
* Collections have default constructor
* insert_item, resize, total_items, constructors, assignment functions work properly
* swap, insert_item, total_item (including size and color) are defined and work properly
"""
points=8.0

[adapters.gtest]
name="SWAP"
testfile="swap.cpp"
