title="Destructor"
description="""
destructor – destroys a collection (deallocates allocated memory and resets size and capacity)

Test case:
* Empty collection is created. 
* N number of Stress_ball() is/are inserted using insert_item().
* Destructor is called.

If this case does not pass, you can check if:
* Collections have default constructor which accepts capacity as argument.
* Destructor, is_empty(), insert_item(), total_tems() is defined and working properly
* parameterized constructor of Stress_ball class is working properly.
* delete[] keyword is used properly at appropriate places.
"""
points=3.0

[adapters.gtest]
name="DESTRUCTOR"
testfile="destructor.cpp"
