title="make_empty()"
description="""
make the collection empty as a helper function to the destructor (deallocate allocated memory):
void make_empty();

Test case:
* Collection object is created.
* items are inserted with insert_item()
* make_empty() clears the Collection object.

If this case does not pass, you can check if:
* Collection constructor is well defined.
* insert_item() , stess_ball constructors, is_empty() are working properly.
"""
points=0.4

[adapters.gtest]
name="MAKE_EMPTY"
testfile="make_empty.cpp"
